apiVersion: v1
kind: extensionPoint
metadata:
  id: com.linkedin.person.panel
  version: 0.0.1
  name: LinkedIn Profile Panel
  description: Add a panel to the LinkedIn user profile page
  author: pixiebrix
definition:
  type: panel
  reader: com.linkedin.person.summary
  isAvailable:
    matchPatterns: https://*.linkedin.com/*
    selectors: "#profile-content"
  defaultOptions:
    caption: "Custom Panel for {{firstName}}"
  containerSelector: ".profile-detail"
  position: prepend
  template: |
    <div class="pixiebrix pv-deferred-area">
      <div class="pv-deferred-area__content">
        <section class="pv-profile-section artdeco-container-card ember-view">
          <h2 class="pv-profile-section__card-heading" data-toggle="collapse" data-target="#{{bodyUUID}}">{{heading}}</h2>
          {{&body}}
        </section>
      </div>
    </div>
