name: Upload zipped Artifact
description: Matches actions/upload-artifact, except it compress files with zip prior to uploading to improve the speed of upload

inputs:
  name:
    description: Name of the artifact file
    default: artifact
    required: false
  path:
    description: A file, directory or wildcard pattern that describes what to upload.
    default: "."
  directory:
    description: |
      Working directory before zipping, refer to `thedoctor0/zip-release` for usage
      https://github.com/TheDoctor0/zip-release
    default: "."
  exclusions:
    description: |
      Globs to exclude, refer to `thedoctor0/zip-release` for usage
      https://github.com/TheDoctor0/zip-release
    required: true
  if-no-files-found:
    default: warn
    required: false
  retention-days:
    required: false

runs:
  using: "composite"
  steps:
    - uses: thedoctor0/zip-release@4fb9e4ff72847dd3d1c111cf63834e353ed7cb3d # Review updates manually
      with:
        filename: ${{ inputs.name }}.zip
        path: ${{ inputs.path }}
        directory: ${{ inputs.directory }}
        exclusions: ${{ inputs.exclusions }}

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}-artifact
        path: ${{ inputs.directory }}/${{ inputs.name }}.zip
        if-no-files-found: ${{ inputs.if-no-files-found }}
        retention-days: ${{ inputs.retention-days }}

    - run: rm ${{ inputs.directory }}/${{ inputs.name }}.zip
      shell: "bash"
