apiVersion: v1
kind: component
metadata:
  id: pixiebrix/examples-pipedrive-person-activity
  version: 0.0.1
  name: Pipedrive Person Activity
  description: A table of activity from Pipedrive for a person
  author: pixiebrix
inputSchema:
  $schema: "https://json-schema.org/draft/2019-09/schema#"
  type: object
  properties:
    pipedrive:
      $ref: "https://app.pixiebrix.com/schemas/services/pipedrive"
    personName:
      type: string
      description: The name of person
    organizationName:
      type: string
      description: The name of the organization to refine the search (optional)
  required:
    - pipedrive
    - personName
pipeline:
  - id: pixiebrix/contrib-pipedrive-persons-search
    config:
      pipedriveService: pipedrive
      name: personName
      organization: organizationName
  - id: pixiebrix/contrib-api
    config:
      accountName: pipedrive
      url: https://api.pipedrive.com/v1/persons/{{id}}/activities
  - id: pixiebrix/contrib-jq
    config:
      filter: "[.data[]?]"
  - id: pixiebrix/contrib-table
    config:
      columns:
        - property: subject
          label: Title
        - property: type
          label: Type
        - property: deal_title
          label: Deal
          # FIXME: this is probably broken. Need a way of referring to inputs within the row
          href: "https://{{@input.pipedrive.subdomain}}.pipedrive.com/deal/{{deal_id}}"
        - property: due_date
          label: Due
