apiVersion: v1
kind: reader
metadata:
  id: com.linkedin.person.contactInfo
  version: 0.0.1
  name: LinkedIn Contact Info
  description: Read contact info from the LinkedIn contact info pane
  author: pixiebrix
definition:
  reader:
    type: emberjs
    selector: ".pv-contact-info"
    attrs: contactInfo
  isAvailable:
    matchPatterns: "https://*.linkedin.com/*"
    selectors: "#profile-content"
outputSchema:
  type: object
  properties:
    entityUrn:
      type: string
      format: uri
    websites:
      type: 'null'
    phoneNumbers:
      type: array
      items:
        type: object
        properties:
          number:
            type: string
          type:
            type: string
    address:
      type: 'null'
    emailAddress:
      type: string
      format: email
    twitterHandles:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
    ims:
      type: 'null'
    connectedAt:
      type: integer
    weChatContactInfo:
      type: 'null'
    birthDateOn:
      type: object
      properties:
        month:
          type: integer
        day:
          type: integer
        year:
          type: integer
